# Generated by Django 5.0.6 on 2024-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
